#!/bin/bash

# Test data for manual verification
echo "=== Mortgage Calculator Test Data ==="
echo "Replace 'your-app-name' with your actual Azure Static Web App name"
echo ""

echo "Test Case 1:"
echo "  Property Price: $500,000"
echo "  Down Payment: $100,000"
echo "  Interest Rate: 5.5%"
echo "  Loan Term: 30 years"
echo "  Expected Monthly Payment: ~$2,271"
echo ""

echo "Test Case 2:"
echo "  Property Price: $650,000"
echo "  Down Payment: $150,000"
echo "  Interest Rate: 6.0%"
echo "  Loan Term: 30 years"
echo "  Expected Monthly Payment: ~$2,998"
echo ""

echo "Test Case 3:"
echo "  Property Price: $350,000"
echo "  Down Payment: $70,000"
echo "  Interest Rate: 5.0%"
echo "  Loan Term: 15 years"
echo "  Expected Monthly Payment: ~$2,214"
echo ""

echo "Test Case 4:"
echo "  Property Price: $800,000"
echo "  Down Payment: $200,000"
echo "  Interest Rate: 7.2%"
echo "  Loan Term: 30 years"
echo "  Expected Monthly Payment: ~$4,073"
echo ""

echo "Test Case 5:"
echo "  Property Price: $450,000"
echo "  Down Payment: $50,000"
echo "  Interest Rate: 6.5%"
echo "  Loan Term: 30 years"
echo "  Expected Monthly Payment: ~$2,528"
echo ""

echo "Test Case 6:"
echo "  Property Price: $250,000"
echo "  Down Payment: $50,000"
echo "  Interest Rate: 4.8%"
echo "  Loan Term: 15 years"
echo "  Expected Monthly Payment: ~$1,558"
echo ""

echo "=== Instructions ==="
echo "1. Open your Azure app: https://your-app-name.azurestaticapps.net"
echo "2. Test each case manually by entering the values"
echo "3. Or run automated tests with: npm run test:e2e"
