#!/bin/bash

# Test data for manual verification - Updated with comprehensive scenarios
echo "=== Mortgage Calculator Test Data ==="
echo "Replace 'your-app-name' with your actual Azure Static Web App name"
echo ""

echo "Test Case 1 - Basic Mortgage:"
echo "  Property Price: $150,000"
echo "  Down Payment: $30,000 (20%)"
echo "  Loan Amount: $120,000"
echo "  Interest Rate: 3.5%"
echo "  Loan Term: 25 years"
echo "  Expected Monthly P&I: ~$600.38"
echo ""

echo "Test Case 2 - Large Loan Amount:"
echo "  Property Price: $500,000"
echo "  Down Payment: $100,000 (20%)"
echo "  Loan Amount: $400,000"
echo "  Interest Rate: 4.2%"
echo "  Loan Term: 30 years"
echo "  Expected Monthly P&I: ~$1,957.01"
echo ""

echo "Test Case 3 - Shorter Term Loan:"
echo "  Property Price: $200,000"
echo "  Down Payment: $40,000 (20%)"
echo "  Loan Amount: $160,000"
echo "  Interest Rate: 3.0%"
echo "  Loan Term: 15 years"
echo "  Expected Monthly P&I: ~$1,106.18"
echo ""

echo "Test Case 4 - High Interest Rate:"
echo "  Property Price: $120,000"
echo "  Down Payment: $24,000 (20%)"
echo "  Loan Amount: $96,000"
echo "  Interest Rate: 5.5%"
echo "  Loan Term: 20 years"
echo "  Expected Monthly P&I: ~$653.23"
echo ""

echo "Test Case 5 - Low Loan Amount, Adjustable Rate:"
echo "  Property Price: $75,000"
echo "  Down Payment: $15,000 (20%)"
echo "  Loan Amount: $60,000"
echo "  Interest Rate: 2.8%"
echo "  Loan Term: 10 years"
echo "  Expected Monthly P&I: ~$576.87"
echo ""

echo "Test Case 6 - Interest-Only Mortgage:"
echo "  Property Price: $250,000"
echo "  Down Payment: $50,000 (20%)"
echo "  Loan Amount: $200,000"
echo "  Interest Rate: 4.0%"
echo "  Loan Term: 25 years"
echo "  Expected Monthly P&I: ~$666.67 (Interest-only)"
echo ""

echo "Test Case 7 - High Loan-to-Value (LTV) Ratio:"
echo "  Property Price: $400,000"
echo "  Down Payment: $50,000 (12.5%)"
echo "  Loan Amount: $350,000"
echo "  Interest Rate: 4.5%"
echo "  Loan Term: 30 years"
echo "  Expected Monthly P&I: ~$1,773.40"
echo ""

echo "Test Case 8 - Low LTV Ratio:"
echo "  Property Price: $250,000"
echo "  Down Payment: $150,000 (60%)"
echo "  Loan Amount: $100,000"
echo "  Interest Rate: 3.75%"
echo "  Loan Term: 20 years"
echo "  Expected Monthly P&I: ~$591.88"
echo ""
echo "  Interest Rate: 4.8%"
echo "  Loan Term: 15 years"
echo "  Expected Monthly Payment: ~$1,558"
echo ""

echo "=== Instructions ==="
echo "1. Open your Azure app: https://your-app-name.azurestaticapps.net"
echo "2. Test each case manually by entering the values"
echo "3. Or run automated tests with: npm run test:e2e"
